#!/usr/bin/env bash
# manage.sh — build, start, stop, cleanup the personal site container.
#
# Designed to run on a Fedora server with Podman.
# Requires CLOUDFLARED_TOKEN in the environment (or in ./.env).
#
# Usage:
#   ./manage.sh build      # build the image
#   ./manage.sh start      # build (if needed) + run detached
#   ./manage.sh stop       # stop the running container
#   ./manage.sh restart    # stop + start
#   ./manage.sh logs       # follow container logs
#   ./manage.sh status     # show container status
#   ./manage.sh install    # install as a systemd service (Quadlet) — auto-start on boot
#   ./manage.sh uninstall  # remove the systemd service
#   ./manage.sh cleanup    # stop + remove container, image, and dangling layers

set -euo pipefail

IMAGE_NAME="${IMAGE_NAME:-personalsite}"
IMAGE_TAG="${IMAGE_TAG:-latest}"
CONTAINER_NAME="${CONTAINER_NAME:-personalsite}"
APP_PORT="${APP_PORT:-8000}"
SERVICE_NAME="${SERVICE_NAME:-personalsite}"
QUADLET_DIR="${QUADLET_DIR:-${HOME}/.config/containers/systemd}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

# Load .env if present (so CLOUDFLARED_TOKEN can live there)
if [[ -f .env ]]; then
  set -a
  # shellcheck disable=SC1091
  . ./.env
  set +a
fi

require_token() {
  if [[ -z "${CLOUDFLARED_TOKEN:-}" ]]; then
    echo "ERROR: CLOUDFLARED_TOKEN is not set." >&2
    echo "Set it in your shell or in a .env file next to this script." >&2
    exit 1
  fi
}

cmd_build() {
  echo ">> Building ${IMAGE_NAME}:${IMAGE_TAG}"
  podman build -t "${IMAGE_NAME}:${IMAGE_TAG}" -f Containerfile .
}

cmd_start() {
  require_token

  if podman container exists "${CONTAINER_NAME}"; then
    echo ">> Container '${CONTAINER_NAME}' already exists; removing first"
    podman rm -f "${CONTAINER_NAME}" >/dev/null
  fi

  if ! podman image exists "${IMAGE_NAME}:${IMAGE_TAG}"; then
    cmd_build
  fi

  echo ">> Starting ${CONTAINER_NAME} (no host port published — reachable via cloudflared)"
  podman run -d \
    --name "${CONTAINER_NAME}" \
    --restart unless-stopped \
    -e "APP_PORT=${APP_PORT}" \
    -e "CLOUDFLARED_TOKEN=${CLOUDFLARED_TOKEN}" \
    "${IMAGE_NAME}:${IMAGE_TAG}"

  echo ">> Started. Use './manage.sh logs' to follow output."
}

cmd_stop() {
  if podman container exists "${CONTAINER_NAME}"; then
    echo ">> Stopping ${CONTAINER_NAME}"
    podman stop "${CONTAINER_NAME}" >/dev/null
    podman rm "${CONTAINER_NAME}" >/dev/null
    echo ">> Stopped and removed."
  else
    echo ">> Container '${CONTAINER_NAME}' is not running."
  fi
}

cmd_restart() {
  cmd_stop
  cmd_start
}

cmd_logs() {
  podman logs -f "${CONTAINER_NAME}"
}

cmd_status() {
  podman ps -a --filter "name=^${CONTAINER_NAME}$"
}

cmd_cleanup() {
  echo ">> Cleaning up container, image, and dangling layers"
  if podman container exists "${CONTAINER_NAME}"; then
    podman rm -f "${CONTAINER_NAME}" >/dev/null || true
  fi
  if podman image exists "${IMAGE_NAME}:${IMAGE_TAG}"; then
    podman rmi -f "${IMAGE_NAME}:${IMAGE_TAG}" >/dev/null || true
  fi
  podman image prune -f >/dev/null || true
  echo ">> Cleanup complete."
}

cmd_install() {
  require_token

  # Build image first so the systemd unit has something to run
  if ! podman image exists "${IMAGE_NAME}:${IMAGE_TAG}"; then
    cmd_build
  fi

  # Stop any running ad-hoc container so it doesn't conflict with the service
  if podman container exists "${CONTAINER_NAME}"; then
    echo ">> Removing existing ad-hoc container '${CONTAINER_NAME}'"
    podman rm -f "${CONTAINER_NAME}" >/dev/null
  fi

  mkdir -p "${QUADLET_DIR}"
  local unit_file="${QUADLET_DIR}/${SERVICE_NAME}.container"

  echo ">> Writing Quadlet unit: ${unit_file}"
  cat > "${unit_file}" <<EOF
# Generated by manage.sh — do not edit by hand.
# Re-run './manage.sh install' to regenerate.

[Unit]
Description=Personal Site (Flask + cloudflared)
After=network-online.target
Wants=network-online.target

[Container]
ContainerName=${CONTAINER_NAME}
Image=localhost/${IMAGE_NAME}:${IMAGE_TAG}
Environment=APP_PORT=${APP_PORT}
Environment=CLOUDFLARED_TOKEN=${CLOUDFLARED_TOKEN}

[Service]
Restart=always
RestartSec=5
TimeoutStartSec=120

[Install]
WantedBy=default.target
EOF
  chmod 600 "${unit_file}"

  # Allow user services to run after logout / on boot
  if command -v loginctl >/dev/null 2>&1; then
    if ! loginctl show-user "$(id -un)" 2>/dev/null | grep -q '^Linger=yes'; then
      echo ">> Enabling lingering for user '$(id -un)' (requires sudo)"
      sudo loginctl enable-linger "$(id -un)"
    fi
  fi

  echo ">> Reloading user systemd"
  systemctl --user daemon-reload

  echo ">> Starting ${SERVICE_NAME}.service"
  systemctl --user start "${SERVICE_NAME}.service"

  echo
  echo ">> Installed. The container will now:"
  echo "     - start automatically at boot"
  echo "     - restart automatically on crash (Restart=always)"
  echo "     - keep running when you log out (linger enabled)"
  echo
  echo "   Manage it with:"
  echo "     systemctl --user status  ${SERVICE_NAME}.service"
  echo "     systemctl --user restart ${SERVICE_NAME}.service"
  echo "     journalctl --user -u    ${SERVICE_NAME}.service -f"
}

cmd_uninstall() {
  local unit_file="${QUADLET_DIR}/${SERVICE_NAME}.container"

  if systemctl --user list-units --all | grep -q "${SERVICE_NAME}.service"; then
    echo ">> Stopping ${SERVICE_NAME}.service"
    systemctl --user stop "${SERVICE_NAME}.service" || true
  fi

  if [[ -f "${unit_file}" ]]; then
    echo ">> Removing Quadlet unit: ${unit_file}"
    rm -f "${unit_file}"
  fi

  systemctl --user daemon-reload
  echo ">> Service uninstalled."
}

usage() {
  cat <<EOF
Usage: $0 {build|start|stop|restart|logs|status|install|uninstall|cleanup}

Environment variables (override defaults):
  IMAGE_NAME       (default: personalsite)
  IMAGE_TAG        (default: latest)
  CONTAINER_NAME   (default: personalsite)
  APP_PORT         (default: 8000, internal only — not published to host)
  SERVICE_NAME     (default: personalsite)
  CLOUDFLARED_TOKEN  (required for 'start' and 'install')

You can also place these in a .env file next to this script.
EOF
}

case "${1:-}" in
  build)     cmd_build ;;
  start)     cmd_start ;;
  stop)      cmd_stop ;;
  restart)   cmd_restart ;;
  logs)      cmd_logs ;;
  status)    cmd_status ;;
  install)   cmd_install ;;
  uninstall) cmd_uninstall ;;
  cleanup)   cmd_cleanup ;;
  *)         usage; exit 1 ;;
esac
